- R/gtrends.R
- This remove potential errors associated with unsuccessful login.
- Also display error message if connection is not working (even is `verbose = TRUE`)
This will closes #32
> stronger verification of login using SID

- NEWS.md
- R/gtrends.R
This was crashing before. Looks like Google will sometimes remove keywords from the returned data.
```r
head(gtrends(c("cat", "flood risk management"), geo = "GB")$trend)
```
https://www.google.fr/trends/explore#q=cat%2C%20flood%20risk%20management&geo=GB&cmpt=q&tz=Etc%2FGMT-1
> Long keywords

- R/gtrends.R
```r
> head(gtrends(c("cat", "flood risk management"), geo = "GB")$trend)
start        end cat.GB flood.risk.management.GB
1 2004-01-04 2004-01-10     48                       NA
2 2004-01-11 2004-01-17     43                       NA
3 2004-01-18 2004-01-24     44                       NA
4 2004-01-25 2004-01-31     44                       NA
5 2004-02-01 2004-02-07     41                       NA
6 2004-02-08 2004-02-14     44                       NA
Warning message:
No data returned for 'flood risk management' keyword(s). 
```
> adding columns with NA values when requested kw are not returned

- NEWS.md
- R/gtrends.R
> fallback for google.{user,password} (closes #121)

- NEWS.md
- R/gtrends.R
Now correctly parse thousand comma separator.
This:
```r
> trends$Rising.searches.for.google
facebook Breakout
1      google chrome Breakout
2    google tradutor Breakout
3               maps Breakout
4        maps google Breakout
5            youtube Breakout
6   translate google       +3
7               800%         
8          translate       +3
9               750%         
10      google earth       +3
11              600%         
12 traduction google       +1
13              350%   
```
becomes:
```r
> trends$Rising.searches.for.google
facebook Breakout
1    google chrome Breakout
2     google earth Breakout
3  google tradutor Breakout
4          youtube Breakout
5             maps   +4800%
6      google play   +4550%
7      google maps   +3500%
8        translate   +3300%
9 google …
```
> Correctly parsing blocks that use the comma thousand separator (closes #133)

- R/gtrends.R
- R/zzz.R
- man/gtrends.Rd
``` r
library(gtrendsR)
head(gtrends(c("NHL", "NFL"), gprop = "news")$interest_over_time)
#>         date hits keyword   geo gprop
#> 1 2012-02-26   11     NHL world  news
#> 2 2012-03-04    5     NHL world  news
#> 3 2012-03-11    5     NHL world  news
#> 4 2012-03-18    5     NHL world  news
#> 5 2012-03-25    6     NHL world  news
#> 6 2012-04-01    7     NHL world  news
head(gtrends(c("NHL", "NFL"), gprop = "youtube")$interest_over_time)
#>         date hits keyword   geo   gprop
#> 1 2012-02-26   27     NHL world youtube
#> 2 2012-03-04   25     NHL world youtube
#> 3 2012-03-11   23     NHL world youtube
#> 4 2012-03-18   25     NHL world youtube
#> 5 2012-03-25   25     NHL world youtube
#> 6 2012-04-01   28     NHL world youtube
```
> gtrends now considers gprop (news, youtube, etc)

- R/gtrends.R
- R/related_queries.R
- R/related_topics.R
- man/gtrends.Rd
``` r
library(gtrendsR)
head(gtrends("NHL")$interest_over_time)
#>         date hits keyword   geo gprop
#> 1 2012-03-11   45     NHL world   web
#> 2 2012-03-18   47     NHL world   web
#> 3 2012-03-25   50     NHL world   web
#> 4 2012-04-01   58     NHL world   web
#> 5 2012-04-08   83     NHL world   web
#> 6 2012-04-15   89     NHL world   web
head(gtrends("NHL")$related_topics)
#>                           subject related_topics value
#> 1          National Hockey League            top   100
#> 2 National Basketball Association            top     5
#> 3            Stanley Cup Playoffs            top     5
#> 4                      Ice hockey            top     5
#> 5           Major League Baseball            top     0
#> 6                             NFL            top     0 …
```
> extract related topics and related queries (closes #174)

- R/related_queries.R
- R/related_topics.R
- R/zzz.R
``` r
library(gtrendsR)
res <- gtrends("", category = "1267", geo = "NO", time = "all")
lapply(res, head)
#> $interest_over_time
#>         date hits keyword geo gprop category
#> 1 2004-01-01   88          NO   web     1267
#> 2 2004-02-01   87          NO   web     1267
#> 3 2004-03-01   60          NO   web     1267
#> 4 2004-04-01   65          NO   web     1267
#> 5 2004-05-01   65          NO   web     1267
#> 6 2004-06-01   83          NO   web     1267
#> 
#> $interest_by_region
#> NULL
#> 
#> $interest_by_dma
#> NULL
#> 
#> $interest_by_city
#> NULL
#> 
#> $related_topics
#>   subject related_topics         value geo category
#> 1     100            top           Car  NO     1267
#> 2      80            top Specification  NO     1267
#> 3      45            top    Combustion  NO …
```
> can query categories without keywords (closes #173 #179)

- R/gtrends.R
- R/zzz.R
Hi, 
To avoid confusion, I re-created this PL after the main branch had the resolution to the non-ASCII characters. 
--- Language and coding ---
There are three issues here:
- The hl= parameter for gtrends() is verified in gtrends.R line 108
- it is now passed on correctly to the get_widget()
- it is passed on in the url request (this was missing, it was set constantly to en-US, even when the user sent a fr-FR) 
- the widget then passes on this information to other zzz function like get interest over time or region.
The hl (locale) parameter does have some effect on what is returned not only in terms of data, but also metadata. 
I can confirm that the new non-ASCII fix works with the search term, but there is still some problem in the metadata, for example, the names of subregions, if …
> Language locale resolved

- NEWS.md
- R/categories.R
- R/countries.R
- R/gtrends.R
- R/related_queries.R
- R/related_topics.R
- R/zzz.R
- data-raw/process_data.R
- It is now possible to use DMA (`gtrends(keyword="obama",geo="US-AL-630")`) (#238)
- Added missing country codes (#213)
- Can now mix both country and sub country codes (`plot(gtrends("pizza", geo = c("CA", "GB-ENG")))`) (#218)
- New parameter `low_search_volume` allowing low search volume regions (#229). 
- Fixing breaking changes that were introduced by Google Trends (#252) @kevinmager65.
> Low search volume

- R/gtrends.R
- R/zzz.R
- man/gtrends.Rd
Allow to search for categories without specifying keywords.
``` r
library(gtrendsR)
plot(gtrends(category = "20"))
```
Created on 2018-02-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
> Search without keywords (closes #249).

- R/zzz.R
I've never written an R package before, so I'm not sure this is best practice. But it creates the necessary cookie handler and fixes get_widget().
In particular, these are the questionable lines: 
```
assign("cookie_handler", cookie_handler, envir = gtrendsR:::.__NAMESPACE__.) # i'm guessing this is bad practice but it works
if(!exists("cookie_handler", envir = gtrendsR:::.__NAMESPACE__.)){ get_api_cookies() }
widget <- curl::curl_fetch_memory(url, handle = gtrendsR:::.__NAMESPACE__.$cookie_handler) # I'm not sure you're supposed to do this but it works
```
I couldn't figure out a good way to create the handler that would be safe from the global environment. I can't create things in the namespace of the package because it is locked. I couldn't find anything online as to best practice for …
> Fixes cookie handling issue introduced on 2018-05-28

- R/gtrends.R
- R/zzz.R
- man/gtrends.Rd
It looks like the NID cookie from trends.google.com, as used in https://github.com/GeneralMills/pytrends and recommended by @RKushnir, is preferable to the more general api.google.com cookie I had used. As noted by @bbakk14, the former works behind a firewall that blocks social media, whereas the latter does not (apparently because it includes Google+?).
Therefore, I changed the default. And, in case users want to use other URLs, I added it as a parameter (with the NID URL being the default) to the top-level function, gtrends() (and updated the man page). In the future, if the URL changes, we can simply change it in the default set by the gtrends() function.
> Changed default cookie URL; added it as a parameter for top-level function

- R/gtrends.R
When relative search interest is less than 1, the hits column returns "<1" and changes the data type to `chr`. The resulting output of `plot.gtrends` ends up failing. This change (line 219) removes the '<' and ensures the column is numeric when plotting without altering the actual `gtrends` object.
> Coherce hits column to numeric

- NEWS.md
- R/zzz.R
There is a small problem when mixing search terms and topic ids. In that the payload2 in the interest_over_time()-function cannot be built since the returned widget from the get_widget()-function is off by one unit. I have fixed it in the zzz.R file temporarily. Perhaps there is a better way to deal with it. I added a reproducible example in the comments.
> Mixing topic and search keywords

- R/zzz.R
> Bug fix keyword encoding when there are multiple keywords with '&'

- NEWS.md
- R/gtrends.R
- R/related_queries.R
- R/related_topics.R
- R/zzz.R
Now you can do stuff like this:
https://support.google.com/trends/answer/4359582?hl=en
I commented the url_encode function, since I do not know why it is there... I think it shouldn't... but please tell me...
best, jb
> Widget-Download:  Characters like + are not encoded properly in the keyword

- .travis.yml
- NEWS.md
Well done on fixing that other bug so quickly!  
Here is just a minor update based on work I was doing this weekend to update the r-travis `run.sh` script to use R 4.0.0.  Already tested / used in three other repos and should be ready.  
The underlying script is still driven a variable `R_VERSION` that still defaults to 3.5 to not (yet, at least) force all repos over, and here we opt in with an explicit 4.0.  Hope its transparent.
> switch Travis CI to R 4.0.0

- .Rbuildignore
- .github/workflows/ci.yaml
- README.md
This adds GitHub Actions for macOS and Linux in a simple, straightforward and portable manner.
~We can add a badge if we wan~A new badge had been added to the README too:  [![ci](https://github.com/PMassicotte/gtrendsR/actions/workflows/ci.yaml/badge.svg)](https://github.com/PMassicotte/gtrendsR/actions/workflows/ci.yaml)
> Add ci.yaml with r-ci based run.sh for linux and macos

- inst/tinytest/test_encoding_does_not_change.R
- inst/tinytest/test_gprop.R
- inst/tinytest/test_not_empty_results.R
- inst/tinytest/test_timespans.R
This PR is a little radical in that all tests are now conditional on being explicitly opted in via a new environment variable.
This may help at CRAN.  The `curl` issue seems random _and even hit me here_ but was easily fixed by a re-run.  This may be an issue in `curl`, seen "randomly" at at least the CRAN Debian machine and here under ubuntu-latest.
I am wondering if you should add a simple "lighter" unit test file with _something_ not involving a `curl` call so that we always have "something" to run?
Also, if you merge the previous PR I can rebase it in here so that this PR gets the benefit of the tests.
> this opts out of all four test files unless opted in

- R/related_queries.R
- R/related_topics.R
- R/zzz.R
This simple PR implements what was suggested in #199, and seems to still behave in my tests and in CI.
> Add 'encoding = "UTF-8"' to read.csv calls (closes #199)
